DEFAULT_OLLAMA_MODEL = "qwen3.5:2b"
DEFAULT_OLLAMA_BASE_URL = "http://localhost:11434/v1"

DEFAULT_CHUNK_SIZE = 1000
DEFAULT_CHUNK_OVERLAP = 200

DEFAULT_VECTORSTORE_NAME = "chromadb_collection"

DEFAULT_NB_RETRIEVED_CHUNKS = 5
